### ISSUE TITLE
Support symfony 6

### ISSUE THREAD

**Issue by aszenz** [BolZer/symfony-typescript-routes#10]
The symfony config component is constrained to ^5.3, could we bump it to allow 6.0 also

**Comment by BolZer** [comment]
Sure thing. A new version will be published shortly. It'll bump the requirement to symfony 6 and php 8.1

**Comment by BolZer** [comment]
@aszenz https://github.com/BolZer/symfony-typescript-routes/releases/tag/1.4.0 there you go.
