### ISSUE TITLE
Incorrect union type generated for route with requirements

### ISSUE THREAD

**Issue by aszenz** [BolZer/symfony-typescript-routes#12]
For this routes requirements :

```
#[Route(path: '/generate/{intent}/{documents}', requirements: ['intent' => 'new_email|email|print|printdebug|preview|preview_data|preview_text|gct.legalize'], options: ['expose' => true])]
```

I expect the `intent` type to be: 
`'new_email'|'email'|'print'|'printdebug'|'preview'|'preview_data'|'preview_text'|'gct.legalize'`

But it generates this:
`'email'|'email'`

**Comment by BolZer** [comment]
Thanks for bringing this to my attention. I'll take a look at this issue and release a new version with bugfixes shortly.

**Comment by BolZer** [comment]
@aszenz 1.4.1 is ready to be upgraded to. This will fix your issue.

**Comment by aszenz** [comment]
Thanks for the speedy fix
