### ISSUE TITLE
Support for more precise types for route arguments

### ISSUE THREAD

**Issue by aszenz** [BolZer/symfony-typescript-routes#7]
Using symfony routes we can specify requirements for route arguments like 

```
#[Route(path: '/search/{kind}/{relation}', requirements: ['kind' => 'I|V', 'relation' => '\d+'], defaults: ['type' => 'V'])]
```

Using these requirements we can further narrow down the generated types for the route

So the type for the `kind` would be `I|V` instead of `string`
similarly relation should be `number` instead of `string`
Maybe we can also add the defaults for each route argument as well.

**Comment by BolZer** [comment]
Hi @aszenz, 

thanks again for your interest in this lib. 

> Using symfony routes we can specify requirements for route arguments like
> 
> ```
> #[Route(path: '/search/{kind}/{relation}', requirements: ['kind' => 'I|V', 'relation' => '\d+'], defaults: ['type' => 'V'])]
> ```
> 
> Using these requirements we can further narrow down the generated types for the route
> 
> So the type for the `kind` would be `I|V` instead of `string` similarly relation should be `number` instead of `string` Maybe we can also add the defaults for each route argument as well.

I'll release a new version after the weekend which supports this. It'll narrow down the types and support defaults.

**Comment by BolZer** [comment]
@aszenz Version 1.2 is released. Support for more precise types and ofc defaults are implemented. 
On a side note: If you generate absolute urls the missing scheme will no longer throw an exception. 
If no scheme is supplied the scheme will be promoted to a route param which must be supplied.

**Comment by aszenz** [comment]
Thanks, cool. Works perfectly.
It would be really to also have a way to auto generate translations in typescript from symfony, but maybe that's an idea for another package.
There is a very cool package for elm which already does this
https://github.com/mdevlamynck/elm-symfony-bridge
